version: "3.8"
services:
  oracle-server:
    build:
      context: ./oracle
      dockerfile: Dockerfile
    networks:
      my_network:
        ipv4_address: 172.20.0.2
    restart: always
    environment:
      ORACLE_PASSWORD: "0000"

  springboot-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    networks:
      my_network:
        ipv4_address: 172.20.0.3
    ports:
      - "9999:9999"
    restart: always
    environment:
      ORACLE_PASSWORD: "0000"

networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"
          gateway: "172.20.0.1"
