--------------------------------------------------------
--  파일이 생성됨 - 월요일-4월-01-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBER_ROLE
--------------------------------------------------------

  CREATE TABLE "ADDIN"."MEMBER_ROLE" 
   (	"ROLE_ID" NUMBER(19,0), 
	"ROLE_NAME" VARCHAR2(45 BYTE), 
	"MEMBER_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ADDIN.MEMBER_ROLE
SET DEFINE OFF;
Insert into ADDIN.MEMBER_ROLE (ROLE_ID,ROLE_NAME,MEMBER_ID) values (41,'ROLE_USER',271);
Insert into ADDIN.MEMBER_ROLE (ROLE_ID,ROLE_NAME,MEMBER_ID) values (42,'ROLE_USER',272);
Insert into ADDIN.MEMBER_ROLE (ROLE_ID,ROLE_NAME,MEMBER_ID) values (40,'ROLE_ADMIN',272);
--------------------------------------------------------
--  DDL for Index MEMBER_ROLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADDIN"."MEMBER_ROLE_PK" ON "ADDIN"."MEMBER_ROLE" ("ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MEMBER_ROLE
--------------------------------------------------------

  ALTER TABLE "ADDIN"."MEMBER_ROLE" ADD CONSTRAINT "MEMBER_ROLE_PK" PRIMARY KEY ("ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEMBER_ROLE
--------------------------------------------------------

  ALTER TABLE "ADDIN"."MEMBER_ROLE" ADD CONSTRAINT "FK34G7EPQLCXQLOEWKU3AOQHHMG" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "ADDIN"."MEMBER" ("MEMBER_ID") ENABLE;
