--------------------------------------------------------
--  파일이 생성됨 - 월요일-4월-01-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MOVIE_THEATER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MOVIE_THEATER"
   (	"MOVIE_ID" NUMBER(19,0), 
	"THEATER_ID" NUMBER(19,0), 
	"ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SYSTEM.MOVIE_THEATER
SET DEFINE OFF;
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (453,2,658);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (453,4,659);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (453,6,660);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (362,3,369);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (362,13,370);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (363,1,371);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (363,5,372);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (364,1,373);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (364,4,374);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (364,3,375);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (364,8,376);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (364,5,377);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (365,2,378);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (366,10,379);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (366,9,380);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (367,9,381);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (367,7,382);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (367,1,383);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (367,6,384);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (368,12,385);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (368,9,386);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (368,13,387);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (369,6,388);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (369,4,389);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (369,11,390);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (369,13,391);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (370,9,392);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (370,10,393);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (370,13,394);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (370,6,395);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (371,9,396);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (371,6,397);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (372,6,398);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (372,9,399);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (373,12,400);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (374,4,401);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (374,5,402);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (374,13,403);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (374,3,404);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (374,9,405);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (375,10,406);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (375,9,407);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (375,11,408);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (376,4,409);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (376,8,410);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (376,2,411);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (377,11,412);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (377,13,413);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (377,4,414);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (377,9,415);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (378,7,416);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (379,4,417);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (379,6,418);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (379,13,419);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (379,1,420);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (380,4,421);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (381,9,422);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (381,3,423);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (381,4,424);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (382,13,425);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (383,11,426);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (383,8,427);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (384,2,428);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (384,13,429);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (384,7,430);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (384,4,431);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (385,1,432);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (385,13,433);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (385,4,434);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (385,3,435);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (385,12,436);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (386,1,437);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (386,2,438);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (387,10,439);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (387,6,440);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (387,2,441);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (388,6,442);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (388,13,443);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (388,2,444);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (388,12,445);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (389,10,446);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (389,9,447);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (389,11,448);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (389,3,449);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (389,6,450);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (390,12,451);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (391,1,452);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (391,4,453);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (391,12,454);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (391,13,455);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (391,2,456);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (392,3,457);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (393,12,458);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (393,5,459);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (394,13,460);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (394,8,461);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (395,4,462);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (395,3,463);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (395,13,464);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (395,10,465);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (396,9,466);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (396,8,467);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (396,11,468);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (396,7,469);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (397,2,470);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (397,1,471);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (397,6,472);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (397,12,473);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (398,7,474);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (398,3,475);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (398,1,476);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (398,5,477);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (399,3,478);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (399,10,479);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (399,13,480);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (399,2,481);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (400,9,482);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (400,7,483);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (400,10,484);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (400,1,485);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (401,11,486);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (401,12,487);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (401,6,488);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (401,4,489);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (402,7,490);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (402,8,491);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (402,1,492);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (402,6,493);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (403,3,494);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (403,8,495);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (403,7,496);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (403,9,497);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (404,8,498);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (404,1,499);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (404,10,500);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (404,6,501);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (405,7,502);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (405,8,503);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (405,5,504);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (405,2,505);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (406,8,506);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (406,1,507);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (406,4,508);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (406,6,509);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (407,4,510);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (407,5,511);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (407,10,512);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (407,12,513);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (407,3,514);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (408,12,515);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (408,10,516);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (408,3,517);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (408,2,518);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (408,13,519);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (409,4,520);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (409,9,521);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (410,4,522);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (410,13,523);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (410,11,524);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (411,7,525);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (411,11,526);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (411,13,527);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (411,6,528);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (411,3,529);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (412,1,530);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (412,2,531);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (413,12,532);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (413,5,533);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (413,7,534);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (414,12,535);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (414,2,536);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (414,11,537);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (415,11,538);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (415,5,539);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (415,3,540);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (416,7,541);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (416,5,542);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (417,8,543);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (418,2,544);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (418,13,545);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (418,3,546);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (419,3,547);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (419,2,548);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (419,8,549);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (419,12,550);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (420,6,551);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (420,5,552);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (420,7,553);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (420,13,554);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (421,7,555);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (421,11,556);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (421,12,557);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (422,8,558);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (423,7,559);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (423,1,560);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (424,5,561);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (424,1,562);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (424,9,563);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (425,5,564);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (426,4,565);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (427,3,566);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (427,11,567);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (428,5,568);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (428,7,569);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (429,5,570);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (429,8,571);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (429,10,572);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (430,2,573);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (430,10,574);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (430,7,575);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (430,5,576);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (430,8,577);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (431,1,578);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (431,7,579);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (432,5,580);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (433,1,581);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (433,5,582);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (433,10,583);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (433,7,584);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (433,9,585);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (434,10,586);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (434,7,587);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (434,2,588);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (434,11,589);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (434,3,590);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (435,13,591);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (435,5,592);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (436,7,593);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (437,12,594);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (437,2,595);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (438,13,596);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (438,1,597);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (438,3,598);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (438,8,599);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (439,2,600);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (439,13,601);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (439,7,602);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (440,7,603);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (440,1,604);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (441,4,605);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (441,1,606);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (441,11,607);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (441,8,608);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (441,2,609);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (442,12,610);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (443,2,611);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (444,10,612);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (444,8,613);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (445,12,614);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (445,11,615);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (446,9,616);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (446,8,617);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (446,13,618);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (446,7,619);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (446,2,620);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (447,13,621);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (447,7,622);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (448,8,623);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (448,5,624);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (448,3,625);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (448,2,626);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (449,1,627);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (449,5,628);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (449,3,629);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (450,8,630);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (450,10,631);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (451,13,632);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (451,12,633);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (451,2,634);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (452,8,635);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (452,1,636);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (453,3,637);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (453,5,638);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (453,9,639);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (453,1,640);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (454,11,641);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (454,2,642);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (454,10,643);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (454,1,644);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (454,5,645);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (455,4,646);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (455,7,647);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (455,12,648);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (455,13,649);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (455,6,650);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (456,9,651);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (456,2,652);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (456,10,653);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (362,1,654);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (362,10,655);
Insert into SYSTEM.MOVIE_THEATER (MOVIE_ID,THEATER_ID,ID) values (363,9,656);
--------------------------------------------------------
--  DDL for Index SYS_C008459
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008459" ON "SYSTEM"."MOVIE_THEATER" ("MOVIE_ID", "THEATER_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MOVIE_THEATER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MOVIE_THEATER" MODIFY ("MOVIE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MOVIE_THEATER" MODIFY ("THEATER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MOVIE_THEATER" ADD PRIMARY KEY ("MOVIE_ID", "THEATER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SYSTEM"."MOVIE_THEATER" MODIFY ("ID" NOT NULL ENABLE);
