--------------------------------------------------------
--  파일이 생성됨 - 월요일-4월-01-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "ADDIN"."MEMBER" 
   (	"IS_WITHDRAWN" CHAR(1 BYTE) DEFAULT 'N', 
	"CREATED_AT" TIMESTAMP (6), 
	"MEMBER_ID" NUMBER(19,0), 
	"MODIFIED_AT" TIMESTAMP (6), 
	"WITHDRAWN_AT" TIMESTAMP (6), 
	"EMAIL" VARCHAR2(255 CHAR), 
	"HOME_ADDRESS" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR), 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"PHONE_NUMBER" VARCHAR2(255 CHAR), 
	"USERNAME" VARCHAR2(255 CHAR), 
	"PROVIDER" VARCHAR2(255 CHAR), 
	"PROVIDER_ID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ADDIN.MEMBER
SET DEFINE OFF;
Insert into ADDIN.MEMBER (IS_WITHDRAWN,CREATED_AT,MEMBER_ID,MODIFIED_AT,WITHDRAWN_AT,EMAIL,HOME_ADDRESS,NAME,PASSWORD,PHONE_NUMBER,USERNAME,PROVIDER,PROVIDER_ID) values ('N',to_timestamp('24/04/01 15:13:08.502904000','RR/MM/DD HH24:MI:SSXFF'),271,null,null,null,null,null,'$2a$10$JHEsBxfxTcREG3x3bFH0HOikMtE9bjFeEjrJt9B2vvUkGiMD.5zHK',null,'user',null,null);
Insert into ADDIN.MEMBER (IS_WITHDRAWN,CREATED_AT,MEMBER_ID,MODIFIED_AT,WITHDRAWN_AT,EMAIL,HOME_ADDRESS,NAME,PASSWORD,PHONE_NUMBER,USERNAME,PROVIDER,PROVIDER_ID) values ('N',to_timestamp('24/04/01 15:14:25.780321000','RR/MM/DD HH24:MI:SSXFF'),272,null,null,null,null,null,'$2a$10$SuBH3ySPaCIxJjMBlh11De0EApNoTHpKqtZRM4wV.ni7I7HDf6CNa',null,'admin',null,null);
--------------------------------------------------------
--  DDL for Index MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADDIN"."MEMBER_PK" ON "ADDIN"."MEMBER" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008390
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADDIN"."SYS_C008390" ON "ADDIN"."MEMBER" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "ADDIN"."MEMBER" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "ADDIN"."MEMBER" ADD PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADDIN"."MEMBER" ADD CONSTRAINT "MEMBER_PK" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
